version: '3.6'

services:

  engine:
    container_name: 'flask-ecommerce-furniture-app'
    build:
      context: ./
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://flaskecommercefurnitureuserprod:flaskecommercefurniturepasswordprod@engine-db:5432/flask_ecommerce_furniture_prod
      - DATABASE_TEST_URL=postgres://flaskecommercefurnitureuserprod:flaskecommercefurniturepasswordprod@engine-db:5432/flask_ecommerce_furniture_test
    depends_on:
      - engine-db

  engine-db:
    container_name: 'flask-ecommerce-furniture-db'
    build:
      context: services/db
      dockerfile: Dockerfile-prod
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=flaskecommercefurnitureuserprod
      - POSTGRES_PASSWORD=flaskecommercefurniturepasswordprod

  nginx:
    container_name: 'flask-ecommerce-furniture-nginx'
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - engine
