"""empty message

Revision ID: f9db2f4b2c39
Revises: 9fa3296993ad
Create Date: 2020-01-17 23:18:24.050140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9db2f4b2c39'
down_revision = '9fa3296993ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_top_product', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_top_product')
    # ### end Alembic commands ###
